spring.application.name=SpringE_Com

spring.datasource.url=jdbc:postgresql://localhost:5432/springecom
spring.datasource.username=postgres
spring.datasource.password=180704@db

spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.auto-commit=false